"""category fix

Revision ID: 068372d0a39c
Revises: bd49345d3cc6
Create Date: 2026-05-30 12:59:04.128645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068372d0a39c'
down_revision: Union[str, Sequence[str], None] = 'bd49345d3cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('is_base', sa.Boolean(), nullable=False))
    op.drop_column('entries', 'side')
    
    sa.Enum('INCOMING', 'OUTGOING', 'TRANSFER', name='transactiondirection').create(op.get_bind())

    op.alter_column('transactions', 'direction',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('INCOMING', 'OUTGOING', 'TRANSFER', name='transactiondirection'),
               existing_nullable=False,
               postgresql_using='direction::transactiondirection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'direction',
               existing_type=sa.Enum('INCOMING', 'OUTGOING', 'TRANSFER', name='transactiondirection'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('entries', sa.Column('side', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('entries', 'is_base')
    # ### end Alembic commands ###
    
    sa.Enum('INCOMING', 'OUTGOING', 'TRANSFER', name='transactiondirection').drop(op.get_bind())