"""temporary trans

Revision ID: 0a6e8b7bdb48
Revises: 7bded2fa3401
Create Date: 2026-05-27 21:03:25.304831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6e8b7bdb48'
down_revision: Union[str, Sequence[str], None] = '7bded2fa3401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_temporary', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_temporary')
    # ### end Alembic commands ###
