"""fix

Revision ID: 2f80986ea1a0
Revises: cc22c0e38253
Create Date: 2026-05-27 23:56:09.110869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f80986ea1a0'
down_revision: Union[str, Sequence[str], None] = 'cc22c0e38253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default='1',
               existing_nullable=False)
    op.alter_column('entries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default='HUF',
               existing_nullable=False)
    op.alter_column('imports', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imports', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('entries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entries', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
