"""test2

Revision ID: 33d155bc3dda
Revises: 973d4b7da83f
Create Date: 2026-04-17 14:27:39.401384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d155bc3dda'
down_revision: Union[str, Sequence[str], None] = '973d4b7da83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    
    account_table = sa.table("accounts",
                             sa.column("name", sa.String),
                             sa.column("side", sa.String),
                             sa.column("test", sa.String))
    op.bulk_insert(account_table, [
                    {"name":"mbh","side":"Assets","test":"asd"},
                    {"name":"erste","side":"Assets","test":"dsa"}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'test')
    # ### end Alembic commands ###
