"""nochange

Revision ID: 43bc8e612bb7
Revises: 51c89b0f8966
Create Date: 2026-04-18 08:21:42.864081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bc8e612bb7'
down_revision: Union[str, Sequence[str], None] = '51c89b0f8966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    op.execute("truncate table accounts restart identity cascade")

    account_table = sa.table("accounts",
                             sa.column("id", sa.Integer),
                             sa.column("parent_id", sa.Integer),
                             sa.column("name", sa.String),
                             sa.column("side", sa.String),
                             sa.column("path", sa.String))
    op.bulk_insert(account_table, [
                    {"id":1,"parent_id":None,"name":"Liquid","side":"Assets","path":"Assets:Liquid"},
                        {"id":2,"parent_id":1,"name":"ErsteDebit","side":"Assets","path":"Assets:Liquid:ErsteDebit"},
                        {"id":3,"parent_id":1,"name":"ErsteHitel","side":"Assets","path":"Assets:Liquid:ErsteHitel"},
                        {"id":4,"parent_id":1,"name":"ErsteWizz","side":"Assets","path":"Assets:Liquid:ErsteWizz"},
                        {"id":5,"parent_id":1,"name":"MbhDebit","side":"Assets","path":"Assets:Liquid:MbhDebit"},
                        {"id":6,"parent_id":1,"name":"MbhCredit","side":"Assets","path":"Assets:Liquid:MbhCredit"},
                        {"id":7,"parent_id":1,"name":"LloydsDebit","side":"Assets","path":"Assets:Liquid:LloydsDebit"},
                        {"id":8,"parent_id":1,"name":"OtpSzep","side":"Assets","path":"Assets:Liquid:OtpSzep"},
                        {"id":9,"parent_id":1,"name":"RevoHUF","side":"Assets","path":"Assets:Liquid:RevoHUF"},
                        {"id":10,"parent_id":1,"name":"RevoGBP","side":"Assets","path":"Assets:Liquid:RevoGBP"},
                        {"id":11,"parent_id":1,"name":"RevoEUR","side":"Assets","path":"Assets:Liquid:RevoEUR"},
                        {"id":12,"parent_id":1,"name":"Cash","side":"Assets","path":"Assets:Liquid:Cash"},
                        {"id":13,"parent_id":1,"name":"Wise","side":"Assets","path":"Assets:Liquid:Wise"},
                    {"id":14,"parent_id":None,"name":"Investment","side":"Assets","path":"Assets:Investment"},
                        {"id":15,"parent_id":14,"name":"ErsteBroker","side":"Assets","path":"Assets:Investment:ErsteBroker"},
                        {"id":16,"parent_id":14,"name":"Binance","side":"Assets","path":"Assets:Investment:Binance"},
                        {"id":17,"parent_id":14,"name":"Mak","side":"Assets","path":"Assets:Investment:Mak"},
                        {"id":18,"parent_id":14,"name":"OtpLtp","side":"Assets","path":"Assets:Investment:OtpLtp"},
                    {"id":19,"parent_id":None,"name":"Receiveables","side":"Assets","path":"Assets:Receiveables"},
                        {"id":20,"parent_id":19,"name":"Tibi","side":"Assets","path":"Assets:Receiveables:Tibi"},
                        {"id":21,"parent_id":19,"name":"Anya","side":"Assets","path":"Assets:Receiveables:Anya"},
                        {"id":22,"parent_id":19,"name":"Clift","side":"Assets","path":"Assets:Receiveables:Clift"},

                    {"id":23,"parent_id":None,"name":"StudentLoan","side":"Liabilities","path":"Liabilities:StudentLoan"},

                    {"id":24,"parent_id":None,"name":"OpeningBalance","side":"Equity","path":"Equity:OpeningBalance"},

                    {"id":25,"parent_id":None,"name":"Salary","side":"Income","path":"Income:Salary"},
                    {"id":26,"parent_id":None,"name":"Clift","side":"Income","path":"Income:Clift"},
                    {"id":27,"parent_id":None,"name":"Stat","side":"Income","path":"Income:Stat"},
                    {"id":28,"parent_id":None,"name":"Other","side":"Income","path":"Income:Other"},

                    {"id":29,"parent_id":None,"name":"Uncategorised","side":"Expenses","path":"Expenses:Uncategorised"},
                ])
    
    op.execute("SELECT setval(pg_get_serial_sequence('accounts','id'), (select max(id) from accounts))")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
