"""transaction sourceid

Revision ID: 50fd92935582
Revises: 068372d0a39c
Create Date: 2026-06-02 15:06:15.002320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fd92935582'
down_revision: Union[str, Sequence[str], None] = '068372d0a39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_path_key'), 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_path'), 'accounts', ['path'], unique=True)
    op.add_column('transactions', sa.Column('source_raw_import_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'raw_imports', ['source_raw_import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'source_raw_import_id')
    op.drop_index(op.f('ix_accounts_path'), table_name='accounts')
    op.create_unique_constraint(op.f('accounts_path_key'), 'accounts', ['path'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
