"""delete test

Revision ID: 51c89b0f8966
Revises: 33d155bc3dda
Create Date: 2026-04-17 15:52:52.923057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c89b0f8966'
down_revision: Union[str, Sequence[str], None] = '33d155bc3dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'test')
    # ### end Alembic commands ###


    account_table = sa.table("accounts",
                             sa.column("name", sa.String),
                             sa.column("side", sa.String))
    op.bulk_insert(account_table, [
                    {"name":"mbh","side":"Assets"},
                    {"name":"erste","side":"Assets"}])




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('test', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
