"""insert config

Revision ID: 753bb62fe227
Revises: 43bc8e612bb7
Create Date: 2026-04-18 10:26:36.772277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753bb62fe227'
down_revision: Union[str, Sequence[str], None] = '43bc8e612bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    account_table = sa.table("account_configs",
                             sa.column("account_id", sa.Integer),
                             sa.column("parser", sa.String))
    op.bulk_insert(account_table, [
                    {"account_id":2,"parser":"parse_erste"},
                    {"account_id":3,"parser":"parse_erste"},
                    {"account_id":4,"parser":"parse_erste"},
                    {"account_id":5,"parser":"parse_mbh"},
                    {"account_id":6,"parser":"parse_mbh"},
                    {"account_id":7,"parser":"parse_lloyds"},
                    {"account_id":8,"parser":"parse_otp_szep"},
                    {"account_id":9,"parser":"parse_revo"},
                    {"account_id":10,"parser":"parse_revo"},
                    {"account_id":11,"parser":"parse_revo"},
                    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
