"""rules rename

Revision ID: 7bded2fa3401
Revises: 753080d6de1c
Create Date: 2026-05-14 19:10:06.824349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bded2fa3401'
down_revision: Union[str, Sequence[str], None] = '753080d6de1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('target_account_id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rule')
    # ### end Alembic commands ###
    
    account_table = sa.table("rules",
                             sa.column("account_id", sa.Integer),
                             sa.column("target_account_id", sa.Integer),
                             sa.column("condiitons", sa.JSON))
    op.bulk_insert(account_table, [
                    {"account_id":8,"target_account_id":"Liquid","condiitons":"Assets"},
    ])

    op.execute(
        "UPDATE account_configs SET raw_extension = 'xlsx' WHERE id = 7"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('rule_account_id_fkey')),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], name=op.f('rule_target_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_pkey'))
    )
    op.drop_table('rules')
    # ### end Alembic commands ###
