"""imports table

Revision ID: a56a5752b06a
Revises: 753bb62fe227
Create Date: 2026-04-19 13:14:22.283687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56a5752b06a'
down_revision: Union[str, Sequence[str], None] = '753bb62fe227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=True),
    sa.Column('min_date', sa.DateTime(), nullable=True),
    sa.Column('max_date', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account_configs', sa.Column('raw_extension', sa.String(length=100), server_default='csv', nullable=False))
    op.add_column('raw_imports', sa.Column('import_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'raw_imports', 'imports', ['import_id'], ['id'])
    op.drop_column('raw_imports', 'source_filename')
    op.add_column('transactions', sa.Column('source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source')
    op.add_column('raw_imports', sa.Column('source_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'raw_imports', type_='foreignkey')
    op.drop_column('raw_imports', 'import_id')
    op.drop_column('account_configs', 'raw_extension')
    op.drop_table('imports')
    # ### end Alembic commands ###
