"""cascade entry delete

Revision ID: b129ce45b073
Revises: 0a6e8b7bdb48
Create Date: 2026-05-27 21:14:18.129305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b129ce45b073'
down_revision: Union[str, Sequence[str], None] = '0a6e8b7bdb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entries_transaction_id_fkey'), 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key(op.f('entries_transaction_id_fkey'), 'entries', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
