"""tr categories

Revision ID: bd49345d3cc6
Revises: 2f80986ea1a0
Create Date: 2026-05-30 12:14:19.980441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd49345d3cc6'
down_revision: Union[str, Sequence[str], None] = '2f80986ea1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('side', sa.String(length=255), nullable=False))
    op.add_column('transactions', sa.Column('direction', sa.String(length=255), nullable=False))
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('transactions', 'direction')
    op.drop_column('entries', 'side')
    # ### end Alembic commands ###
