"""add rules

Revision ID: cc22c0e38253
Revises: b129ce45b073
Create Date: 2026-05-27 23:07:27.262814

"""
from typing import Sequence, Union
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc22c0e38253'
down_revision: Union[str, Sequence[str], None] = 'b129ce45b073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    
    rule_table = sa.table("rules",
                             sa.column("account_id", sa.Integer),
                             sa.column("target_account_id", sa.Integer),
                             sa.column("conditions", sa.JSON))
    op.bulk_insert(rule_table, [
                    {"account_id":8,"target_account_id":25,"conditions":json.dumps({"Ellenoldali név":"Mazars Kft."})},
                    {"account_id":8,"target_account_id":25,"conditions":json.dumps({"Ellenoldali név":"Forvis Mazars Kft"})},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
