"""manual accounts

Revision ID: e6cfa39ef02b
Revises: 50fd92935582
Create Date: 2026-06-04 16:45:15.934338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cfa39ef02b'
down_revision: Union[str, Sequence[str], None] = '50fd92935582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    account_table = sa.table("accounts",
                             sa.column("id", sa.Integer),
                             sa.column("parent_id", sa.Integer),
                             sa.column("name", sa.String),
                             sa.column("side", sa.String),
                             sa.column("path", sa.String))
    op.bulk_insert(account_table, [
                    {"id":31,"parent_id":None,"name":"Shopping","side":"Expenses","path":"Expenses:Shopping"},
                        {"id":32,"parent_id":31,"name":"Hypermarket","side":"Expenses","path":"Expenses:Shopping:Hypermarket"},
                        {"id":33,"parent_id":31,"name":"Drogerie","side":"Expenses","path":"Expenses:Shopping:Drogerie"},
                        {"id":55,"parent_id":31,"name":"Food","side":"Expenses","path":"Expenses:Shopping:Food"},
                    {"id":34,"parent_id":None,"name":"Subscription","side":"Expenses","path":"Expenses:Subscription"},
                        {"id":35,"parent_id":34,"name":"HBO","side":"Expenses","path":"Expenses:Subscription:HBO"},
                        {"id":36,"parent_id":34,"name":"Netflix","side":"Expenses","path":"Expenses:Subscription:Netflix"},
                        {"id":37,"parent_id":34,"name":"Spotify","side":"Expenses","path":"Expenses:Subscription:Spotify"},
                        {"id":38,"parent_id":34,"name":"Gym","side":"Expenses","path":"Expenses:Subscription:Gym"},
                        {"id":39,"parent_id":34,"name":"Telekom","side":"Expenses","path":"Expenses:Subscription:Telekom"},
                        {"id":40,"parent_id":34,"name":"Flat","side":"Expenses","path":"Expenses:Subscription:Flat"},
                    {"id":41,"parent_id":None,"name":"Fees","side":"Expenses","path":"Expenses:Fees"},
                    {"id":42,"parent_id":None,"name":"Commute","side":"Expenses","path":"Expenses:Commute"},
                        {"id":43,"parent_id":42,"name":"BKV","side":"Expenses","path":"Expenses:Commute:BKV"},
                        {"id":44,"parent_id":42,"name":"Train","side":"Expenses","path":"Expenses:Commute:Train"},
                    {"id":45,"parent_id":None,"name":"Luxury","side":"Expenses","path":"Expenses:Luxury"},
                        {"id":46,"parent_id":45,"name":"Wellness","side":"Expenses","path":"Expenses:Luxury:Wellness"},
                        {"id":47,"parent_id":45,"name":"AI","side":"Expenses","path":"Expenses:Luxury:AI"},
                        {"id":48,"parent_id":45,"name":"Eatout","side":"Expenses","path":"Expenses:Luxury:Eatout"},
                        {"id":49,"parent_id":45,"name":"Gym","side":"Expenses","path":"Expenses:Luxury:Gym"},
                        {"id":50,"parent_id":45,"name":"Books","side":"Expenses","path":"Expenses:Luxury:Books"},
                        {"id":51,"parent_id":45,"name":"Clothes","side":"Expenses","path":"Expenses:Luxury:Clothes"},
                        {"id":52,"parent_id":45,"name":"Electronics","side":"Expenses","path":"Expenses:Luxury:Electronics"},
                        {"id":53,"parent_id":45,"name":"Taxi","side":"Expenses","path":"Expenses:Luxury:Taxi"},
                        {"id":54,"parent_id":45,"name":"Gaming}","side":"Expenses","path":"Expenses:Luxury:Gaming"},
                ])
    
    op.execute("SELECT setval(pg_get_serial_sequence('accounts','id'), (select max(id) from accounts))")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
